'use server'

export async function generateMathProblem(topicName: string) {
  const apiKey = process.env.GEMINI_API_KEY || process.env.NEXT_PUBLIC_GEMINI_API_KEY

  if (!apiKey) {
    throw new Error('Gemini API key is not configured')
  }

  const prompt = `Generate a single math practice problem for the topic "${topicName}". 
  The problem should be appropriate for a high school or early college curriculum (Algebra, Calculus, Geometry, etc.).
  
  Return ONLY a raw JSON object (no markdown, no backticks) with these keys:
  - "expression": The problem statement. Use LaTeX formatting for math symbols where appropriate, but keep it readable as plain text if possible. For example, use "∫" for integrals.
  - "instruction": A short instruction like "Solve for x", "Evaluate the integral", "Find the limit".
  - "answer": The correct answer. If it's a number, provide the number. If it's an expression, provide the simplified expression.
  
  Make sure the problem is solvable and the answer is correct.
  Example JSON:
  {
    "expression": "Solve x^2 - 4 = 0",
    "instruction": "Find the positive value of x",
    "answer": "2"
  }`

  try {
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
        }),
      }
    )

    if (!response.ok) {
      const errorText = await response.text()
      console.error('Gemini API Error:', errorText)
      throw new Error(`Gemini API error: ${response.statusText}`)
    }

    const data = await response.json()
    const text = data.candidates?.[0]?.content?.parts?.[0]?.text

    if (!text) {
      throw new Error('No content generated by Gemini')
    }

    // Clean up markdown code blocks if present
    const cleanText = text.replace(/```json/g, '').replace(/```/g, '').trim()
    
    try {
      return JSON.parse(cleanText)
    } catch (parseError) {
      console.error('JSON Parse Error:', cleanText)
      throw new Error('Failed to parse generated problem')
    }
  } catch (error) {
    console.error('Generate Problem Error:', error)
    throw error
  }
}
