
import { Course } from "./curriculum";

export const apCourses: Course[] = [
  {
    id: "ap-capstone",
    name: "AP Capstone Diploma Program",
    units: [
      {
        name: "AP Research",
        topics: [
          { name: "Big Idea 1: Question and Explore", videoId: "" },
          { name: "Identifying a problem and developing a question", videoId: "" },
          { name: "Finding and organizing information", videoId: "" },
          { name: "Evaluating sources", videoId: "" },
          { name: "Examining the problem from multiple perspectives", videoId: "" },
          { name: "Big Idea 2: Understand and Analyze", videoId: "" },
          { name: "Reading critically for a purpose", videoId: "" },
          { name: "Explaining and analyzing arguments", videoId: "" },
          { name: "Evaluating evidence", videoId: "" },
          { name: "Assessing potential resolutions or solutions", videoId: "" },
          { name: "Big Idea 3: Evaluate Multiple Perspectives", videoId: "" },
          { name: "Identifying and comparing different perspectives", videoId: "" },
          { name: "Evaluating objections, implications, and limitations", videoId: "" },
          { name: "Big Idea 4: Synthesize Ideas", videoId: "" },
          { name: "Formulating a well-reasoned argument", videoId: "" },
          { name: "Using data from various sources", videoId: "" },
          { name: "Linking evidence to claims", videoId: "" },
          { name: "Offering conclusions based on evidence", videoId: "" },
          { name: "Big Idea 5: Team, Transform, and Transmit", videoId: "" },
          { name: "Planning, producing, and presenting an argument", videoId: "" },
          { name: "Communicating through appropriate media", videoId: "" },
        ],
      },
      {
        name: "AP Seminar",
        topics: [
          { name: "Unit 1: Introduction to AP Seminar", videoId: "" },
          { name: "Introduction to the QUEST framework", videoId: "" },
          { name: "The Power of Inquiry", videoId: "" },
          { name: "Exploring and Analyzing Arguments", videoId: "" },
          { name: "Unit 2: Building Arguments", videoId: "" },
          { name: "Constructing a well-reasoned argument", videoId: "" },
          { name: "Evaluating sources and evidence", videoId: "" },
          { name: "Synthesizing information", videoId: "" },
          { name: "Unit 3: Engaging with Multiple Perspectives", videoId: "" },
          { name: "Identifying and evaluating different perspectives", videoId: "" },
          { name: "Developing a nuanced understanding of an issue", videoId: "" },
          { name: "Unit 4: Crafting a Research-Based Argument", videoId: "" },
          { name: "Formulating a research question", videoId: "" },
          { name: "Conducting research and gathering information", videoId: "" },
          { name: "Writing a research-based argument paper", videoId: "" },
          { name: "Unit 5: Presenting and Defending Arguments", videoId: "" },
          { name: "Developing and delivering a presentation", videoId: "" },
          { name: "Responding to questions and defending an argument", videoId: "" },
        ],
      },
    ],
  },
  {
    id: "ap-arts",
    name: "Arts",
    units: [
      {
        name: "AP 2-D Art and Design",
        topics: [
          { name: "Unit 1: Inquiry and Investigation", videoId: "" },
          { name: "Generating ideas for art and design", videoId: "" },
          { name: "Investigating materials and processes", videoId: "" },
          { name: "Developing a proposal for a sustained investigation", videoId: "" },
          { name: "Unit 2: Making and Practice", videoId: "" },
          { name: "Experimenting with materials and techniques", videoId: "" },
          { name: "Developing a body of work", videoId: "" },
          { name: "Reflecting on and refining work", videoId: "" },
          { name: "Unit 3: Communication and Reflection", videoId: "" },
          { name: "Presenting and sharing work", videoId: "" },
          { name: "Writing about art and design", videoId: "" },
          { name: "Developing a portfolio", videoId: "" },
        ],
      },
      {
        name: "AP 3-D Art and Design",
        topics: [
          { name: "Unit 1: Inquiry and Investigation", videoId: "" },
          { name: "Generating ideas for art and design", videoId: "" },
          { name: "Investigating materials and processes", videoId: "" },
          { name: "Developing a proposal for a sustained investigation", videoId: "" },
          { name: "Unit 2: Making and Practice", videoId: "" },
          { name: "Experimenting with materials and techniques", videoId: "" },
          { name: "Developing a body of work", videoId: "" },
          { name: "Reflecting on and refining work", videoId: "" },
          { name: "Unit 3: Communication and Reflection", videoId: "" },
          { name: "Presenting and sharing work", videoId: "" },
          { name: "Writing about art and design", videoId: "" },
          { name: "Developing a portfolio", videoId: "" },
        ],
      },
      {
        name: "AP Drawing",
        topics: [
          { name: "Unit 1: Inquiry and Investigation", videoId: "" },
          { name: "Generating ideas for drawing", videoId: "" },
          { name: "Investigating materials and processes", videoId: "" },
          { name: "Developing a proposal for a sustained investigation", videoId: "" },
          { name: "Unit 2: Making and Practice", videoId: "" },
          { name: "Experimenting with materials and techniques", videoId: "" },
          { name: "Developing a body of work", videoId: "" },
          { name: "Reflecting on and refining work", videoId: "" },
          { name: "Unit 3: Communication and Reflection", videoId: "" },
          { name: "Presenting and sharing work", videoId: "" },
          { name: "Writing about drawing", videoId: "" },
          { name: "Developing a portfolio", videoId: "" },
        ],
      },
      {
        name: "AP Art History",
        topics: [
          { name: "Unit 1: Global Prehistory, 30,000–500 B.C.E.", videoId: "" },
          { name: "Unit 2: Ancient Mediterranean, 3500 B.C.E.–300 C.E.", videoId: "" },
          { name: "Unit 3: Early Europe and Colonial Americas, 200–1750 C.E.", videoId: "" },
          { name: "Unit 4: Later Europe and Americas, 1750–1980 C.E.", videoId: "" },
          { name: "Unit 5: Indigenous Americas, 1000 B.C.E.–1980 C.E.", videoId: "" },
          { name: "Unit 6: Africa, 1100–1980 C.E.", videoId: "" },
          { name: "Unit 7: West and Central Asia, 500 B.C.E.–1980 C.E.", videoId: "" },
          { name: "Unit 8: South, East, and Southeast Asia, 300 B.C.E.–1980 C.E.", videoId: "" },
          { name: "Unit 9: The Pacific, 700–1980 C.E.", videoId: "" },
          { name: "Unit 10: Global Contemporary, 1980 C.E. to Present", videoId: "" },
        ],
      },
      {
        name: "AP Music Theory",
        topics: [
          { name: "Unit 1: Music Fundamentals I: Pitch, Major Scales and Key Signatures, Rhythm, Meter, and Expressive Elements", videoId: "" },
          { name: "Unit 2: Music Fundamentals II: Minor Scales and Key Signatures, Melody, Timbre, and Texture", videoId: "" },
          { name: "Unit 3: Music Fundamentals III: Triads and Seventh Chords", videoId: "" },
          { name: "Unit 4: Harmony I: Chord Progressions", videoId: "" },
          { name: "Unit 5: Harmony II: Voice Leading in Four-Part Writing", videoId: "" },
          { name: "Unit 6: Harmony III: Embellishments, Motives, and Melodic Devices", videoId: "" },
          { name: "Unit 7: Form and Analysis", videoId: "" },
          { name: "Unit 8: Putting It All Together", videoId: "" },
        ],
      },
    ],
  },
  {
    id: "ap-english",
    name: "English",
    units: [
      {
        name: "AP English Language and Composition",
        topics: [
          { name: "Unit 1: Rhetorical Analysis", videoId: "" },
          { name: "Unit 2: Argumentation", videoId: "" },
          { name: "Unit 3: Synthesis", videoId: "" },
        ],
      },
      {
        name: "AP English Literature and Composition",
        topics: [
          { name: "Unit 1: Short Fiction", videoId: "" },
          { name: "Unit 2: Poetry I", videoId: "" },
          { name: "Unit 3: Longer Fiction or Drama I", videoId: "" },
          { name: "Unit 4: Longer Fiction or Drama II", videoId: "" },
          { name: "Unit 5: Poetry II", videoId: "" },
        ],
      },
    ],
  },
  {
    id: "ap-history-social-sciences",
    name: "History & Social Sciences",
    units: [
      {
        name: "AP African American Studies",
        topics: [
          { name: "Unit 1: Origins of the African Diaspora", videoId: "" },
          { name: "Unit 2: Freedom, Enslavement, and Resistance", videoId: "" },
          { name: "Unit 3: The Practice of Freedom", videoId: "" },
          { name: "Unit 4: Movements and Debates", videoId: "" },
        ],
      },
      {
        name: "AP Comparative Government and Politics",
        topics: [
          { name: "Unit 1: Political Systems, Regimes, and Governments", videoId: "" },
          { name: "Unit 2: Political Institutions", videoId: "" },
          { name: "Unit 3: Political Culture and Participation", videoId: "" },
          { name: "Unit 4: Party and Electoral Systems and Citizen Organizations", videoId: "" },
          { name: "Unit 5: Political and Economic Changes and Development", videoId: "" },
        ],
      },
      {
        name: "AP European History",
        topics: [
          { name: "Unit 1: Renaissance and Exploration", videoId: "" },
          { name: "Unit 2: Age of Reformation", videoId: "" },
          { name: "Unit 3: Absolutism and Constitutionalism", videoId: "" },
          { name: "Unit 4: Scientific, Philosophical, and Political Developments", videoId: "" },
          { name: "Unit 5: Conflict, Crisis, and Reaction in the Late 18th Century", videoId: "" },
          { name: "Unit 6: Industrialization and Its Effects", videoId: "" },
          { name: "Unit 7: 19th-Century Perspectives and Political Developments", videoId: "" },
          { name: "Unit 8: 20th-Century Global Conflicts", videoId: "" },
          { name: "Unit 9: Cold War and Contemporary Europe", videoId: "" },
        ],
      },
      {
        name: "AP Human Geography",
        topics: [
          { name: "Unit 1: Thinking Geographically", videoId: "" },
          { name: "Unit 2: Population and Migration Patterns and Processes", videoId: "" },
          { name: "Unit 3: Cultural Patterns and Processes", videoId: "" },
          { name: "Unit 4: Political Patterns and Processes", videoId: "" },
          { name: "Unit 5: Agriculture and Rural Land-Use Patterns and Processes", videoId: "" },
          { name: "Unit 6: Cities and Urban Land-Use Patterns and Processes", videoId: "" },
          { name: "Unit 7: Industrial and Economic Development Patterns and Processes", videoId: "" },
        ],
      },
      {
        name: "AP Macroeconomics",
        topics: [
          { name: "Unit 1: Basic Economic Concepts", videoId: "" },
          { name: "Unit 2: Economic Indicators and the Business Cycle", videoId: "" },
          { name: "Unit 3: National Income and Price Determination", videoId: "" },
          { name: "Unit 4: Financial Sector", videoId: "" },
          { name: "Unit 5: Long-Run Consequences of Stabilization Policies", videoId: "" },
          { name: "Unit 6: Open Economy—International Trade and Finance", videoId: "" },
        ],
      },
      {
        name: "AP Microeconomics",
        topics: [
          { name: "Unit 1: Basic Economic Concepts", videoId: "" },
          { name: "Unit 2: Supply and Demand", videoId: "" },
          { name: "Unit 3: Production, Cost, and the Perfect Competition Model", videoId: "" },
          { name: "Unit 4: Imperfect Competition", videoId: "" },
          { name: "Unit 5: Factor Markets", videoId: "" },
          { name: "Unit 6: Market Failure and the Role of Government", videoId: "" },
        ],
      },
      {
        name: "AP Psychology",
        topics: [
          { name: "Unit 1: Scientific Foundations of Psychology", videoId: "" },
          { name: "Unit 2: Biological Bases of Behavior", videoId: "" },
          { name: "Unit 3: Sensation and Perception", videoId: "" },
          { name: "Unit 4: Learning", videoId: "" },
          { name: "Unit 5: Cognitive Psychology", videoId: "" },
          { name: "Unit 6: Developmental Psychology", videoId: "" },
          { name: "Unit 7: Motivation, Emotion, and Personality", videoId: "" },
          { name: "Unit 8: Clinical Psychology", videoId: "" },
          { name: "Unit 9: Social Psychology", videoId: "" },
        ],
      },
      {
        name: "AP United States Government and Politics",
        topics: [
          { name: "Unit 1: Foundations of American Democracy", videoId: "" },
          { name: "Unit 2: Interactions Among Branches of Government", videoId: "" },
          { name: "Unit 3: Civil Liberties and Civil Rights", videoId: "" },
          { name: "Unit 4: American Political Ideologies and Beliefs", videoId: "" },
          { name: "Unit 5: Political Participation", videoId: "" },
        ],
      },
      {
        name: "AP United States History",
        topics: [
          { name: "Unit 1: Period 1: 1491–1607", videoId: "" },
          { name: "Unit 2: Period 2: 1607–1754", videoId: "" },
          { name: "Unit 3: Period 3: 1754–1800", videoId: "" },
          { name: "Unit 4: Period 4: 1800–1848", videoId: "" },
          { name: "Unit 5: Period 5: 1844–1877", videoId: "" },
          { name: "Unit 6: Period 6: 1865–1898", videoId: "" },
          { name: "Unit 7: Period 7: 1890–1945", videoId: "" },
          { name: "Unit 8: Period 8: 1945–1980", videoId: "" },
          { name: "Unit 9: Period 9: 1980–Present", videoId: "" },
        ],
      },
      {
        name: "AP World History: Modern",
        topics: [
          { name: "Unit 1: The Global Tapestry, c. 1200 to c. 1450", videoId: "" },
          { name: "Unit 2: Networks of Exchange, c. 1200 to c. 1450", videoId: "" },
          { name: "Unit 3: Land-Based Empires, c. 1450 to c. 1750", videoId: "" },
          { name: "Unit 4: Transoceanic Interconnections, c. 1450 to c. 1750", videoId: "" },
          { name: "Unit 5: Revolutions, c. 1750 to c. 1900", videoId: "" },
          { name: "Unit 6: Consequences of Industrialization, c. 1750 to c. 1900", videoId: "" },
          { name: "Unit 7: Global Conflict, c. 1900 to the present", videoId: "" },
          { name: "Unit 8: Cold War and Decolonization, c. 1900 to the present", videoId: "" },
          { name: "Unit 9: Globalization, c. 1900 to the present", videoId: "" },
        ],
      },
    ],
  },
  {
    id: "ap-math-computer-science",
    name: "Math & Computer Science",
    units: [
      {
        name: "AP Calculus AB",
        topics: [
          { name: "Unit 1: Limits and Continuity", videoId: "" },
          { name: "Unit 2: Differentiation: Definition and Fundamental Properties", videoId: "" },
          { name: "Unit 3: Differentiation: Composite, Implicit, and Inverse Functions", videoId: "" },
          { name: "Unit 4: Contextual Applications of Differentiation", videoId: "" },
          { name: "Unit 5: Analytical Applications of Differentiation", videoId: "" },
          { name: "Unit 6: Integration and Accumulation of Change", videoId: "" },
          { name: "Unit 7: Differential Equations", videoId: "" },
          { name: "Unit 8: Applications of Integration", videoId: "" },
        ],
      },
      {
        name: "AP Calculus BC",
        topics: [
          { name: "Unit 1: Limits and Continuity", videoId: "" },
          { name: "Unit 2: Differentiation: Definition and Fundamental Properties", videoId: "" },
          { name: "Unit 3: Differentiation: Composite, Implicit, and Inverse Functions", videoId: "" },
          { name: "Unit 4: Contextual Applications of Differentiation", videoId: "" },
          { name: "Unit 5: Analytical Applications of Differentiation", videoId: "" },
          { name: "Unit 6: Integration and Accumulation of Change", videoId: "" },
          { name: "Unit 7: Differential Equations", videoId: "" },
          { name: "Unit 8: Applications of Integration", videoId: "" },
          { name: "Unit 9: Parametric Equations, Polar Coordinates, and Vector-Valued Functions", videoId: "" },
          { name: "Unit 10: Infinite Sequences and Series", videoId: "" },
        ],
      },
      {
        name: "AP Computer Science A",
        topics: [
          { name: "Unit 1: Primitive Types", videoId: "" },
          { name: "Unit 2: Using Objects", videoId: "" },
          { name: "Unit 3: Boolean Expressions and if Statements", videoId: "" },
          { name: "Unit 4: Iteration", videoId: "" },
          { name: "Unit 5: Writing Classes", videoId: "" },
          { name: "Unit 6: Array", videoId: "" },
          { name: "Unit 7: ArrayList", videoId: "" },
          { name: "Unit 8: 2D Array", videoId: "" },
          { name: "Unit 9: Inheritance", videoId: "" },
          { name: "Unit 10: Recursion", videoId: "" },
        ],
      },
      {
        name: "AP Computer Science Principles",
        topics: [
          { name: "Unit 1: The Internet", videoId: "" },
          { name: "Unit 2: Digital Information", videoId: "" },
          { name: "Unit 3: Algorithms and Programming", videoId: "" },
          { name: "Unit 4: Big Data and Privacy", videoId: "" },
          { name: "Unit 5: Building Apps", videoId: "" },
        ],
      },
      {
        name: "AP Precalculus",
        topics: [
          { name: "Unit 1: Polynomial and Rational Functions", videoId: "" },
          { name: "Unit 2: Exponential and Logarithmic Functions", videoId: "" },
          { name: "Unit 3: Trigonometric and Polar Functions", videoId: "" },
          { name: "Unit 4: Functions Involving Parameters, Vectors, and Matrices", videoId: "" },
        ],
      },
      {
        name: "AP Statistics",
        topics: [
          { name: "Unit 1: Exploring One-Variable Data", videoId: "" },
          { name: "Unit 2: Exploring Two-Variable Data", videoId: "" },
          { name: "Unit 3: Collecting Data", videoId: "" },
          { name: "Unit 4: Probability, Random Variables, and Probability Distributions", videoId: "" },
          { name: "Unit 5: Sampling Distributions", videoId: "" },
          { name: "Unit 6: Inference for Categorical Data: Proportions", videoId: "" },
          { name: "Unit 7: Inference for Quantitative Data: Means", videoId: "" },
          { name: "Unit 8: Inference for Categorical Data: Chi-Square", videoId: "" },
          { name: "Unit 9: Inference for Quantitative Data: Slopes", videoId: "" },
        ],
      },
    ],
  },
  {
    id: "ap-sciences",
    name: "Sciences",
    units: [
        { name: "AP Biology", 
        topics: [
          { name: "Unit 1: Chemistry of Life", videoId: "" },
          { name: "Unit 2: Cell Structure and Function", videoId: "" },
          { name: "Unit 3: Cellular Energetics", videoId: "" },
          { name: "Unit 4: Cell Communication and Cell Cycle", videoId: "" },
          { name: "Unit 5: Heredity", videoId: "" },
          { name: "Unit 6: Gene Expression and Regulation", videoId: "" },
          { name: "Unit 7: Natural Selection", videoId: "" },
          { name: "Unit 8: Ecology", videoId: "" },
        ] },
        { name: "AP Chemistry", 
        topics: [
          { name: "Unit 1: Atomic Structure and Properties", videoId: "" },
          { name: "Unit 2: Molecular and Ionic Compound Structure and Properties", videoId: "" },
          { name: "Unit 3: Intermolecular Forces and Properties", videoId: "" },
          { name: "Unit 4: Chemical Reactions", videoId: "" },
          { name: "Unit 5: Kinetics", videoId: "" },
          { name: "Unit 6: Thermodynamics", videoId: "" },
          { name: "Unit 7: Equilibrium", videoId: "" },
          { name: "Unit 8: Acids and Bases", videoId: "" },
          { name: "Unit 9: Applications of Thermodynamics", videoId: "" },
        ] },
        { name: "AP Environmental Science", 
        topics: [
          { name: "Unit 1: The Living World: Ecosystems", videoId: "" },
          { name: "Unit 2: The Living World: Biodiversity", videoId: "" },
          { name: "Unit 3: Populations", videoId: "" },
          { name: "Unit 4: Earth Systems and Resources", videoId: "" },
          { name: "Unit 5: Land and Water Use", videoId: "" },
          { name: "Unit 6: Energy Resources and Consumption", videoId: "" },
          { name: "Unit 7: Atmospheric Pollution", videoId: "" },
          { name: "Unit 8: Aquatic and Terrestrial Pollution", videoId: "" },
          { name: "Unit 9: Global Change", videoId: "" },
        ] },
        { name: "AP Physics 1: Algebra-Based", 
        topics: [
          { name: "Unit 1: Kinematics", videoId: "" },
          { name: "Unit 2: Dynamics", videoId: "" },
          { name: "Unit 3: Circular Motion and Gravitation", videoId: "" },
          { name: "Unit 4: Energy", videoId: "" },
          { name: "Unit 5: Momentum", videoId: "" },
          { name: "Unit 6: Simple Harmonic Motion", videoId: "" },
          { name: "Unit 7: Torque and Rotational Motion", videoId: "" },
        ] },
        { name: "AP Physics 2: Algebra-Based", 
        topics: [
          { name: "Unit 1: Fluids", videoId: "" },
          { name: "Unit 2: Thermodynamics", videoId: "" },
          { name: "Unit 3: Electric Force, Field, and Potential", videoId: "" },
          { name: "Unit 4: Electric Circuits", videoId: "" },
          { name: "Unit 5: Magnetism and Electromagnetic Induction", videoId: "" },
          { name: "Unit 6: Geometric and Physical Optics", videoId: "" },
          { name: "Unit 7: Quantum, Atomic, and Nuclear Physics", videoId: "" },
        ] },
        { name: "AP Physics C: Electricity and Magnetism", 
        topics: [
          { name: "Unit 1: Electrostatics", videoId: "" },
          { name: "Unit 2: Conductors, Capacitors, Dielectrics", videoId: "" },
          { name: "Unit 3: Electric Circuits", videoId: "" },
          { name: "Unit 4: Magnetic Fields", videoId: "" },
          { name: "Unit 5: Electromagnetism", videoId: "" },
        ] },
        { name: "AP Physics C: Mechanics", 
        topics: [
          { name: "Unit 1: Kinematics", videoId: "" },
          { name: "Unit 2: Newton's Laws of Motion", videoId: "" },
          { name: "Unit 3: Work, Energy, and Power", videoId: "" },
          { name: "Unit 4: Systems of Particles and Linear Momentum", videoId: "" },
          { name: "Unit 5: Rotation", videoId: "" },
          { name: "Unit 6: Oscillations", videoId: "" },
          { name: "Unit 7: Gravitation", videoId: "" },
        ] },
    ],
  },
  {
    id: "ap-world-languages-cultures",
    name: "World Languages & Cultures",
    units: [
        { name: "AP Chinese Language and Culture", 
        topics: [
          { name: "Unit 1: Families in Different Societies", videoId: "" },
          { name: "Unit 2: The Influence of Language and Culture on Identity", videoId: "" },
          { name: "Unit 3: Influences of Beauty and Art", videoId: "" },
          { name: "Unit 4: How Science and Technology Affect Our Lives", videoId: "" },
          { name: "Unit 5: Factors That Impact the Quality of Life", videoId: "" },
          { name: "Unit 6: Environmental, Political, and Societal Challenges", videoId: "" },
        ] },
        { name: "AP French Language and Culture", 
        topics: [
          { name: "Unit 1: Families and Communities", videoId: "" },
          { name: "Unit 2: Personal and Public Identities", videoId: "" },
          { name: "Unit 3: Beauty and Aesthetics", videoId: "" },
          { name: "Unit 4: Science and Technology", videoId: "" },
          { name: "Unit 5: Contemporary Life", videoId: "" },
          { name: "Unit 6: Global Challenges", videoId: "" },
        ] },
        { name: "AP German Language and Culture", 
        topics: [
          { name: "Unit 1: Families and Communities", videoId: "" },
          { name: "Unit 2: Personal and Public Identities", videoId: "" },
          { name: "Unit 3: Beauty and Aesthetics", videoId: "" },
          { name: "Unit 4: Science and Technology", videoId: "" },
          { name: "Unit 5: Contemporary Life", videoId: "" },
          { name: "Unit 6: Global Challenges", videoId: "" },
        ] },
        { name: "AP Italian Language and Culture", 
        topics: [
          { name: "Unit 1: Families and Communities", videoId: "" },
          { name: "Unit 2: Personal and Public Identities", videoId: "" },
          { name: "Unit 3: Beauty and Aesthetics", videoId: "" },
          { name: "Unit 4: Science and Technology", videoId: "" },
          { name: "Unit 5: Contemporary Life", videoId: "" },
          { name: "Unit 6: Global Challenges", videoId: "" },
        ] },
        { name: "AP Japanese Language and Culture", 
        topics: [
          { name: "Unit 1: Families and Communities", videoId: "" },
          { name: "Unit 2: Personal and Public Identities", videoId: "" },
          { name: "Unit 3: Beauty and Aesthetics", videoId: "" },
          { name: "Unit 4: Science and Technology", videoId: "" },
          { name: "Unit 5: Contemporary Life", videoId: "" },
          { name: "Unit 6: Global Challenges", videoId: "" },
        ] },
        { name: "AP Latin", 
        topics: [
          { name: "Unit 1: Vergil's Aeneid", videoId: "" },
          { name: "Unit 2: Caesar's Gallic War", videoId: "" },
        ] },
        { name: "AP Spanish Language and Culture", 
        topics: [
          { name: "Unit 1: Families and Communities", videoId: "" },
          { name: "Unit 2: Personal and Public Identities", videoId: "" },
          { name: "Unit 3: Beauty and Aesthetics", videoId: "" },
          { name: "Unit 4: Science and Technology", videoId: "" },
          { name: "Unit 5: Contemporary Life", videoId: "" },
          { name: "Unit 6: Global Challenges", videoId: "" },
        ] },
        { name: "AP Spanish Literature and Culture", 
        topics: [
          { name: "Unit 1: El Siglo de Oro", videoId: "" },
          { name: "Unit 2: El Siglo XIX", videoId: "" },
          { name: "Unit 3: El Siglo XX", videoId: "" },
          { name: "Unit 4: El Teatro y la Poesía del Siglo XX", videoId: "" },
          { name: "Unit 5: La Prosa del Siglo XX", videoId: "" },
          { name: "Unit 6: El Boom Latinoamericano", videoId: "" },
          { name: "Unit 7: Escritoras Contemporáneas de Latinoamérica y España", videoId: "" },
          { name: "Unit 8: Poesía y Teatro del Siglo XXI", videoId: "" },
        ] },
    ],
  },
];
